image: node:20.6.0
cache:
  paths:
    - node_modules/
stages:
  - build
  - .pre
  - dast
  - .post
build:dev:
  image: node:20.6.0
  stage: build
  before_script:
    - apt-get update -qy
    - npm install sass
    - npm -v
    - node -v
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - cd devlite-app
    - rm node_modules -fr
    - npm install
    - npm run build
    - cd ..
    - rm node_modules -fr
    - npm install
    - npm start
  allow_failure: true
  # Add `dast` to your `stages:` configuration
